version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m

  app:
    build: .
    container_name: app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/saludtech/api
      - PULSAR_SERVICE_URL=pulsar://pulsar:6650
    depends_on:
      - pulsar
    command: flask run --host=0.0.0.0
  clients:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/clients/api
    command: flask run --host=0.0.0.0
